spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
      url: jdbc:mysql://localhost:3306/auth_chassi?createDatabaseIfNotExist=true
      username: igor
      password: 12345678

  flyway:
    locations:
      filesystem: db/migration
      validateMigrationNaming: true

rsa:
  private-key: 12345
  public-key: 123

server:
  port: 8081